---
abstract: 'Conversion For Roman Numerals in Perl.'
author:
  - 'Daniel Yacob <dyacob\@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Convert-Number-Roman
provides:
  Convert::Number::Roman:
    file: lib/Convert/Number/Roman.pm
    version: '0.04'
requires:
  perl: v5.8.0
resources:
  bugtracker: https://github.com/dyacob/Convert-Number-Roman/issues
  homepage: https://github.com/dyacob/Convert-Number-Roman
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dyacob/Convert-Number-Roman.git
version: '0.04'
x_authority: cpan:dyacob
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
